Document: 5d
Title: Debian 5d Manual
Author: <insert document author here>
Abstract: This manual describes what 5d is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/5d/5d.sgml.gz

Format: postscript
Files: /usr/share/doc/5d/5d.ps.gz

Format: text
Files: /usr/share/doc/5d/5d.text.gz

Format: HTML
Index: /usr/share/doc/5d/html/index.html
Files: /usr/share/doc/5d/html/*.html
