#!/usr/bin/env python

import sys
def getNames(n):
	result = []
	with open(n, "r") as f:
		for line in f.readlines():
			sys.stdout.write(line)
			if line.find("=") == -1:
				continue
			assert(line.startswith("let "))
			rest = line[len("let ") : ]
			rest = rest[: rest.find("=")].strip()
			name = rest
			result.append(name)
	return(set(result))

l = ["['%s %s]" % (n, n) for n in getNames(sys.argv[1])]
print "dispatchModule $"		
print "[" + ("\n".join(l)) + "]"
