#!/usr/bin/env python

import sys

if len(sys.argv) > 1:
   ccs = [c for c in sys.argv[1]]
else:
   ccs = ["C"]
   
# 32768 alphabet = ["*", "i", "h", "c", "f", "d", "L", "l"]
alphabet = ["p", "i", "h", "l"]

result = []

digits = None
def increaseDigit(v):
  if v is None:
    v = 0
  else:
    v = v + 1
  return(v)
def increase():
    global digits
    i = len(digits) - 1
    digits[i] = increaseDigit(digits[i])
    while i >= 0 and digits[i] >= len(alphabet):
        digits[i] -= len(alphabet)
        i = i - 1
        if i < 0:
            return(False)
        digits[i] = increaseDigit(digits[i])
    return(True)
def reset(cc):
    global digits
    if cc == "P":
        digits = 5 * [None]
    else:
        digits = 5 * [0]
def galphabet(a):
    if a is None:
        return ""
    else:
        return alphabet[a]
extras = [
	"vs",
	"vps",
	"sp",
	"vpp",
	"is",
	"hpipip",
	"iiiiipp",
	"iiiipip",
	"iiipih",
	"iiipip",
	"iiipipi",
	"iiipipisp",
	"iiippi",
	"iiippii",
	"iiippiip",
	"iiippip",
	"iiipppi",
	"iiipspi",
	"iiisip",
	"iiisipi",
	"iiisisi",
	"iiisppi",
	"iipiii",
	"iipiipip",
	"iipipi",
	"iiplppp",
	"iippii",
	"iisipi",
	"ipiiiff",
	"ipiiii",
	"ipiiiii",
	"ipiiiiii",
	"ipiiiiiiii",
	"ipiiiiiiiippi",
	"ipiiiiiiiippii",
	"ipiiiip",
	"ipiiiipiii",
	"ipiiiipiiiii",
	"ipiiiipiipiii",
	"ipiiiipp",
	"ipiiip",
	"ipiiipp",
	"ipiiippip",
	"ipiiipsip",
	"ipiiis",
	"ipiipi",
	"ipiipiiipi",
	"ipiipipp",
	"ipiipp",
	"ipiippp",
	"ipiipppp",
	"ipiippppi",
	"ipiisi",
	"ipiisip",
	"ipiisp",
	"ipipii",
	"ipipip",
	"ipippi",
	"ipippp",
	"ipisii",
	"ippiii",
	"ippiiiii",
	"ippiiippp",
	"ippiip",
	"ippiipi",
	"ippiippi",
	"ippiippp",
	"ippipi",
	"ippipiip",
	"ippipip",
	"ippipipi",
	"ippipipp",
	"ippipp",
	"ippippp",
	"ippippppi",
	"ippphpi",
	"ipppih",
	"ipppii",
	"ipppiiiipii",
	"ipppip",
	"ipppipp",
	"ippplp",
	"ippppi",
	"ippppiii",
	"ippppiiiii",
	"ippppiipppp",
	"ippppip",
	"ippppl",
	"ippppp",
	"ipppppi",
	"ippppppi",
	"ipsiip",
	"ipsiipi",
	"ipsiippp",
	"ipsipi",
	"ipsppp",
	"ipsshpi",
	"ipssih",
	"ipsspl",
	"ispipipi",
	"ispippppi",
	"ispppiipspp",
	"ispppp",
	"isspis",
	"isspppi",
	"isssipp",
	"issspi",
	"issspis",
	"lipiip",
	"lpiiip",
	"lpiipiip",
	"lpiipiipi",
	"lpiisiipi",
	"lppiip",
	"lpppip",
	"lsppip",
	"piiiiii",
	"piiiiiiiiiiiiip",
	"piiiiiiiiiiiiis",
	"piiiip",
	"piipip",
	"pippiiiiipppp",
	"pissiiiiipppp",
	"pllipp",
	"ppiiii",
	"ppiiiiii",
	"ppiiiiiip",
	"ppiiiip",
	"ppiiiipp",
	"ppiipiip",
	"ppipipi",
	"ppippip",
	"pppiii",
	"pppiiii",
	"pppiiiiippp",
	"pppiiip",
	"pppiiis",
	"pppippi",
	"pppippip",
	"pppppp",
	"ppsiiii",
	"ppsppp",
	"psiiiiiip",
	"psiipiip",
	"psipipi",
	"pssiiiiippp",
	"viiiil",
	"ipppipppppp",
]
for cc in ccs:
  reset(cc)
  while True:
      v = ("%s%s%s%s%s%s" % (cc, galphabet(digits[0]), galphabet(digits[1]), galphabet(digits[2]), galphabet(digits[3]), galphabet(digits[4])))
      if len(v) > 1:
        print(v)
      if not increase():
         break
  for extra in extras:
    print("%s%s" % (cc, extra))
    