#!/usr/bin/env python

import sys

if len(sys.argv) > 1:
   ccs = [c for c in sys.argv[1]]
else:
   ccs = ["C"]
   
# 32768 alphabet = ["*", "i", "h", "c", "f", "d", "L", "l"]
alphabet = ["p", "i", "h", "l"]

result = []

digits = 5 * [0]
def increase():
    global digits
    i = len(digits) - 1
    digits[i] += 1
    while i >= 0 and digits[i] >= len(alphabet):
        digits[i] -= len(alphabet)
        i = i - 1
        if i < 0:
            return(False)
        digits[i] += 1
    return(True)
def reset():
    global digits
    digits = 5 * [0]
    
print("Cvs")
print("Cvps")
print("Csp")
print("Cvpp")
print("Cis")

while True:
    print ("C%s%s%s%s%s" % (alphabet[digits[0]], alphabet[digits[1]], alphabet[digits[2]], alphabet[digits[3]], alphabet[digits[4]]))
    if not increase():
       break

    