#!/usr/bin/env python

import sys

def checks(combination):
    result = [combination]
    if combination.startswith("C"):
      c = combination
      while c != "" and c[-1] == "i":
        c = c[:-1]
        result.append(c)
    return(result)

print("""
#include "AST/AST"
#include "AST/Symbol"
namespace Trampolines {
""")
for combination in sys.stdin.readlines():
    combination = combination.rstrip("\n")
    for c in checks(combination):
        print("AST::Symbol* S_%s = AST::symbolFromStr(\"%s\");" % (c, c))
print("};")
